services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-screenshot-sorter
    ports:
      - "5678:5678"
    env_file:
      - config.env
    volumes:
      - n8n_data:/home/node/.n8n
      - SCREENSHOT_PATH_PLACEHOLDER:/data/desktop
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  n8n_data:
    driver: local
